apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-artifactory-dev-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/editkaraszzenseact/argocd-app-config.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: cicd-artifactory

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true ## Should be false / default on dev
      prune: true ## Should be false / default on dev
