apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cicd-artifactory-dev-ingress
  namespace: ingress-nginx
spec:
  ingressClassName: nginx
#  tls:
#  - hosts:
#      - artifactory.dev.com
#    secretName: cicd-artifactory-dev-secret-tls
  rules:
  - host: artifactory.dev.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cicd-artifactory-dev
            port:
              number: 8082
