kind: Service
apiVersion: v1
metadata:
  name: cicd-artifactory-service
spec:
  selector:
    app: artifactory
  ports:
  - name: api-endpoint
    protocol: TCP
    port: 8081 
    targetPort: 8081
  - name: http-endpoint
    protocol: TCP
    port: 80 # DEFAULT it is not necessary to add it
    targetPort: 8082
  - name: federation-sync
    protocol: TCP
    port: 8040
    targetPort: 8040